### PR TITLE
Hardcode concept-uri scheme for wikibase

### PR DESCRIPTION
**Pull request by toban**
Hardcoding ~~Adds support for changing~~ the concept-uri scheme, also bumped the version used in CI to closer reflect the reality of wikibase.cloud

### CODE REVIEW

**Comment by tarrow** [comment]
Trying to keep track of my thinking here:
- after this change CI is still passing but it shouldn't be
- you can see the test log is full of errors about the conceptUri being wrong
- should we update the image to instead use the wbstack/mediawiki image this would "fix" the CI?
- should we tighten the CI to try and understand why the "query" test passes when in reality no data is loaded ?

**Comment by toban** [comment]
> Trying to keep track of my thinking here:
> 
>     * after this change CI is still passing but it shouldn't be
> 
>     * you can see the test log is full of errors about the conceptUri being wrong
> 
>     * should we update the image to instead use the wbstack/mediawiki image this would "fix" the CI?
> 
>     * should we tighten the CI to try and understand why the "query" test passes when in reality no data is loaded ?

Ah bummer, it was working correctly [here](https://github.com/wbstack/queryservice-updater/pull/68/commits/0b6df00448affb08668e2d161140ca9f6f10d4b2) when it was configurable. 

I guess we could either let the default value (no env var around) be HTTP, but that doesn't make much sense since we hardcoded it in the mediawiki side.

Another option would be change the conceptUri in the image we are currently using by loading a LocalSettings.php file in CI, could try swapping it to a known good one of the mediawiki image but not entirely sure thats a drop-in-replacement of the plain wikibase image.

**Comment by toban** [comment]
@tarrow this seems to work

**Review by tarrow — APPROVED** [review]
Looks great; thanks so much for also hardening up the CI in this PR.

**Pull request merged**
